import io
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.enums import TA_CENTER, TA_LEFT
import xlsxwriter


def generate_pdf_report(
    transactions: list[dict],
    summary: dict,
    title: str = "Financial Statement Report",
) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.5 * inch)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("title", parent=styles["Title"], fontSize=18, alignment=TA_CENTER, spaceAfter=12)
    section_style = ParagraphStyle("section", parent=styles["Heading2"], fontSize=12, spaceBefore=12, spaceAfter=6)

    elements = [Paragraph(title, title_style), Spacer(1, 0.2 * inch)]

    # Summary box
    elements.append(Paragraph("Summary", section_style))
    summary_data = [
        ["Institution", summary.get("institution_name", "N/A")],
        ["Period", f"{summary.get('statement_period_start', '')} to {summary.get('statement_period_end', '')}"],
        ["Total Deposits", f"${summary.get('total_deposits', 0):,.2f}"],
        ["Total Withdrawals", f"${summary.get('total_withdrawals', 0):,.2f}"],
        ["Ending Balance", f"${summary.get('ending_balance', 0):,.2f}"],
        ["Transactions", str(len(transactions))],
    ]
    summary_table = Table(summary_data, colWidths=[2.5 * inch, 4 * inch])
    summary_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F3F4F6")),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
                ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#F9FAFB")]),
                ("PADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    elements.extend([summary_table, Spacer(1, 0.3 * inch)])

    if summary.get("ai_summary"):
        elements.append(Paragraph("AI Summary", section_style))
        elements.append(Paragraph(summary["ai_summary"], styles["Normal"]))
        elements.append(Spacer(1, 0.2 * inch))

    # Transactions table
    elements.append(Paragraph("Transactions", section_style))
    headers = ["Date", "Description", "Type", "Category", "Amount"]
    rows = [headers]
    for t in transactions:
        amount_str = f"+${t['amount']:,.2f}" if t["transaction_type"] == "deposit" else f"-${t['amount']:,.2f}"
        rows.append(
            [
                t.get("date", ""),
                (t.get("description", "")[:45] + "...") if len(t.get("description", "")) > 45 else t.get("description", ""),
                t.get("transaction_type", "").title(),
                t.get("ai_category", "").replace("_", " ").title() if t.get("ai_category") else "",
                amount_str,
            ]
        )

    col_widths = [0.9 * inch, 2.8 * inch, 0.9 * inch, 1.3 * inch, 1 * inch]
    txn_table = Table(rows, colWidths=col_widths, repeatRows=1)
    txn_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F2937")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 9),
                ("FONTSIZE", (0, 1), (-1, -1), 8),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F9FAFB")]),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#E5E7EB")),
                ("PADDING", (0, 0), (-1, -1), 4),
                ("ALIGN", (4, 0), (4, -1), "RIGHT"),
            ]
        )
    )
    elements.append(txn_table)

    elements.append(Spacer(1, 0.3 * inch))
    elements.append(
        Paragraph(
            f"Generated by AccountingSuite on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
            ParagraphStyle("footer", parent=styles["Normal"], fontSize=8, textColor=colors.grey, alignment=TA_CENTER),
        )
    )

    doc.build(elements)
    return buffer.getvalue()


def generate_excel_report(transactions: list[dict], summary: dict, title: str = "Financial Report") -> bytes:
    buffer = io.BytesIO()
    workbook = xlsxwriter.Workbook(buffer)

    # Formats
    header_fmt = workbook.add_format({"bold": True, "bg_color": "#1F2937", "font_color": "white", "border": 1})
    money_fmt = workbook.add_format({"num_format": "#,##0.00", "border": 1})
    date_fmt = workbook.add_format({"num_format": "yyyy-mm-dd", "border": 1})
    cell_fmt = workbook.add_format({"border": 1})
    alt_fmt = workbook.add_format({"bg_color": "#F9FAFB", "border": 1})
    alt_money_fmt = workbook.add_format({"num_format": "#,##0.00", "bg_color": "#F9FAFB", "border": 1})

    # Summary sheet
    ws_summary = workbook.add_worksheet("Summary")
    ws_summary.set_column("A:A", 25)
    ws_summary.set_column("B:B", 30)
    ws_summary.write("A1", title, workbook.add_format({"bold": True, "font_size": 14}))
    summary_rows = [
        ("Institution", summary.get("institution_name", "")),
        ("Period Start", summary.get("statement_period_start", "")),
        ("Period End", summary.get("statement_period_end", "")),
        ("Total Deposits", summary.get("total_deposits", 0)),
        ("Total Withdrawals", summary.get("total_withdrawals", 0)),
        ("Ending Balance", summary.get("ending_balance", 0)),
        ("Transaction Count", len(transactions)),
    ]
    for i, (label, value) in enumerate(summary_rows, start=2):
        ws_summary.write(i, 0, label, workbook.add_format({"bold": True}))
        if isinstance(value, (int, float)):
            ws_summary.write(i, 1, value, money_fmt)
        else:
            ws_summary.write(i, 1, value)

    # Transactions sheet
    ws_txn = workbook.add_worksheet("Transactions")
    headers = ["Date", "Description", "Payee", "Type", "Category", "Amount", "Balance After", "Reference", "QB Synced"]
    col_widths = [12, 40, 25, 15, 20, 14, 14, 18, 12]
    for col, (header, width) in enumerate(zip(headers, col_widths)):
        ws_txn.write(0, col, header, header_fmt)
        ws_txn.set_column(col, col, width)

    for row_idx, txn in enumerate(transactions, start=1):
        is_alt = row_idx % 2 == 0
        fmt = alt_fmt if is_alt else cell_fmt
        m_fmt = alt_money_fmt if is_alt else money_fmt
        ws_txn.write(row_idx, 0, txn.get("date", ""), fmt)
        ws_txn.write(row_idx, 1, txn.get("description", ""), fmt)
        ws_txn.write(row_idx, 2, txn.get("payee", ""), fmt)
        ws_txn.write(row_idx, 3, txn.get("transaction_type", "").title(), fmt)
        ws_txn.write(row_idx, 4, (txn.get("ai_category") or "").replace("_", " ").title(), fmt)
        amount = txn.get("amount", 0)
        if txn.get("transaction_type") == "withdrawal":
            amount = -abs(amount)
        ws_txn.write(row_idx, 5, amount, m_fmt)
        ws_txn.write(row_idx, 6, txn.get("balance_after") or "", m_fmt)
        ws_txn.write(row_idx, 7, txn.get("reference_number", ""), fmt)
        ws_txn.write(row_idx, 8, "Yes" if txn.get("qb_synced") else "No", fmt)

    ws_txn.autofilter(0, 0, len(transactions), len(headers) - 1)
    ws_txn.freeze_panes(1, 0)

    workbook.close()
    return buffer.getvalue()
